export default [
  {
    files: ["plugins/**/*.js"],
    ignores: ["plugins/**/*.ts"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        Promise: "readonly",
        Array: "readonly",
        Map: "readonly",
        Set: "readonly",
        Date: "readonly",
        Error: "readonly",
        RegExp: "readonly",
        parseInt: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        exports: "readonly",
        require: "readonly",
        module: "readonly",
        Object: "readonly",
        typeof: "readonly",
        JSON: "readonly",
        Buffer: "readonly",
        URL: "readonly",
        process: "readonly",
        crypto: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        global: "readonly",
        globalThis: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        Uint8Array: "readonly",
        FormData: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        Event: "readonly",
        DragEvent: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        FileReader: "readonly",
        File: "readonly",
        FileList: "readonly",
        Blob: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        AbortController: "readonly",
        URLSearchParams: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        alert: "readonly",
        confirm: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        atob: "readonly",
        btoa: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly"
      }
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-console": "off",
      "semi": ["error", "always"],
      "no-var": "off",
      "prefer-const": "off",
      "eqeqeq": "warn"
    }
  }
];
